general {
    lock_cmd = hyprlock
}

# 30 min sur batterie
listener {
    timeout = 1800
    on-timeout = sh -c '[ "$(cat /sys/class/power_supply/AC/online)" = "0" ] && hyprlock'
}

# 1h sur secteur
listener {
    timeout = 3600
    on-timeout = sh -c '[ "$(cat /sys/class/power_supply/AC/online)" = "1" ] && hyprlock'
}
